### ISSUE TITLE
unzip should use -o -f always or optionally

### ISSUE THREAD

**Issue by tzz** [puppet-community/puppet-staging#81]
Currently, if a file exists, `unzip` will prompt, which is usually the wrong thing.  So the `-o -f` flags should be passed, optionally controlled with `$overwrite` and `$freshen` or whatever.

**Comment by nanliu** [comment]
Let us know if #83 is sufficient.

**Comment by tzz** [comment]
I think the default should be `-o -f` so `unzip` doesn't try to prompt, but #83 is enough for my needs.  Please close if you don't plan to change the default.  Thanks!
