### ISSUE TITLE
Ability to validate checksum and/or file size of archive

### ISSUE THREAD

**Issue by XANi** [puppet-community/puppet-staging#82]
For two reasons:

* Connecting to server via HTTPS doesn't mean the target file was not tampered with and checking checksum can prevent it
* If target file is either "in middle of uploading" or incomplete for some other reason (corrupted disk etc.) it should not load it.

**Comment by nanliu** [comment]
There are ways to provide checksum, but it's rather cumbersome. This is the reason there's a type/provider replacement: https://github.com/puppet-community/puppet-archive
